version: '3.8'

services:
  # Metabase (Tableau de bord)
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    restart: always

  # Azurite (Emulateur Azure Storage)
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    restart: always
    

