version: '3.8'

services:
  # Base de données PostgreSQL pour Airbyte
  airbyte-db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: airbyte
      POSTGRES_PASSWORD: password
      POSTGRES_DB: airbyte
    volumes:
      - airbyte_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Airbyte platform services
  airbyte-server:
    image: airbyte/server:0.50.66
    depends_on:
      - airbyte-db
    environment:
      - AIRBYTE_VERSION=0.50.66
      - DATABASE_HOST=airbyte-db
      - DATABASE_PORT=5432
      - DATABASE_DB=airbyte
      - DATABASE_USER=airbyte
      - DATABASE_PASSWORD=password
      - WORKSPACE_ROOT=/workspace
      - CONFIG_ROOT=/configs
      - TRACKING_STRATEGY=segment
    volumes:
      - airbyte_data:/workspace
      - airbyte_config:/configs
    restart: unless-stopped

  airbyte-webapp:
    image: airbyte/webapp:0.50.66
    ports:
      - "8000:80"
    depends_on:
      - airbyte-server
    environment:
      - AIRBYTE_VERSION=0.50.66
      - API_URL=/api/v1
      - IS_DEMO=false
    restart: unless-stopped

  airbyte-worker:
    image: airbyte/worker:0.50.66
    depends_on:
      - airbyte-db
    environment:
      - AIRBYTE_VERSION=0.50.66
      - DATABASE_HOST=airbyte-db
      - DATABASE_PORT=5432
      - DATABASE_DB=airbyte
      - DATABASE_USER=airbyte
      - DATABASE_PASSWORD=password
      - WORKSPACE_ROOT=/workspace
      - CONFIG_ROOT=/configs
      - TEMPORAL_HOST=airbyte-temporal:7233
    volumes:
      - airbyte_data:/workspace
      - airbyte_config:/configs
    restart: unless-stopped

  airbyte-temporal:
    image: airbyte/temporal:0.50.66
    depends_on:
      - airbyte-db
    environment:
      - AIRBYTE_VERSION=0.50.66
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=airbyte
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=airbyte
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    volumes:
      - airbyte_data:/workspace
    restart: unless-stopped

  # Metabase (Tableau de bord)
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    restart: always

  # Azurite (Emulateur Azure Storage)
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    restart: always

volumes:
  airbyte_db_data:
  airbyte_data:
  airbyte_config:
